version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public/:/var/www/public/
    ports:
      - 8877:80

  php:
    image: php:8.1-fpm
